name = "Flatpack 2"
author = "Shadow"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bc79d0ca56bafededa06f48d2df6208d346174671f2bcdffc1f482b7dfbe88ca"

[versions]
minecraft = "1.20.4"
neoforge = "20.4.237"
