name = "Flatpack 2"
author = "Shadow"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b869c4bd3a663577caa1d10e8d5b3ee0b3bffed474eb633ff15c6ae5fdf4c027"

[versions]
minecraft = "1.20.4"
neoforge = "20.4.237"
