name = "Flatpack 2"
author = "Shadow"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "11d3f7a35d85e1acfa80f9e34dfcb6fe709fef975a66bacc6bf18100d0dcebb0"

[versions]
minecraft = "1.20.4"
neoforge = "20.4.237"
