name = "Flatpack 2"
author = "Shadow"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "89c07db45c209378444c758e8da851eff921c52d9a95c07078fbcb477b168413"

[versions]
minecraft = "1.20.4"
neoforge = "20.4.237"
