name = "Flatpack 2"
author = "Shadow"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "03b7d75e007240a1b0a6acd409f785608997b28fac14fcce90c082d411dbea26"

[versions]
minecraft = "1.20.4"
neoforge = "20.4.237"
