name = "Flatpack 2"
author = "Shadow"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f083dc562a95919a7190cc3fa6aebbeca28da8989ee5f4480fd8a3ebb052b6af"

[versions]
minecraft = "1.20.4"
neoforge = "20.4.237"
