name = "Flatpack 2"
author = "Shadow"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f27064a52bfb8311c035df480e6372ac6bf82f5c893990626d07c1dea0c40518"

[versions]
minecraft = "1.20.4"
neoforge = "20.4.237"
